package com.example.recipieapiandcache.presentation.screens

import com.example.recipieapiandcache.data.local.RecipeEntity

// SampleData.kt
object SampleRecipes {
    val recipeList = listOf(
        RecipeEntity(
            id = 1,
            name = "Pizza",
            ingredients = listOf("Cheese", "Dough", "Tomato Sauce"),
            instructions = listOf("Mix ingredients", "Bake in oven"),
            prepTimeMinutes = 10,
            cookTimeMinutes = 40,
            servings = 2,
            difficulty = "Easy",
            cuisine = "Italian",
            caloriesPerServing = 400,
            tags = listOf("Dinner", "Comfort Food"),
            userId = 1,
            image = "https://cdn.dummyjson.com/recipe-images/1.webp",
            rating = 4.5,
            reviewCount = 120,
            mealType = listOf("Lunch", "Dinner")
        ),
        RecipeEntity(
            id = 2,
            name = "Spaghetti Bolognese",
            ingredients = listOf("Spaghetti", "Ground Beef", "Tomato Sauce"),
            instructions = listOf("Cook pasta", "Cook sauce", "Mix together"),
            prepTimeMinutes = 15,
            cookTimeMinutes = 30,
            servings = 4,
            difficulty = "Medium",
            cuisine = "Italian",
            caloriesPerServing = 500,
            tags = listOf("Dinner"),
            userId = 2,
            image = "https://cdn.dummyjson.com/recipe-images/5.webp",
            rating = 4.6,
            reviewCount = 98,
            mealType = listOf("Dinner")
        ),
        RecipeEntity(
            id = 3,
            name = "Caesar Salad",
            ingredients = listOf("Lettuce", "Croutons", "Parmesan", "Caesar Dressing"),
            instructions = listOf("Chop lettuce", "Add dressing", "Top with croutons and cheese"),
            prepTimeMinutes = 10,
            cookTimeMinutes = 0,
            servings = 2,
            difficulty = "Easy",
            cuisine = "International",
            caloriesPerServing = 200,
            tags = listOf("Healthy", "Lunch"),
            userId = 3,
            image = "https://cdn.dummyjson.com/recipe-images/6.webp",
            rating = 4.2,
            reviewCount = 40,
            mealType = listOf("Lunch")
        ),
        RecipeEntity(
            id = 4,
            name = "Chicken Curry",
            ingredients = listOf("Chicken", "Curry Powder", "Coconut Milk"),
            instructions = listOf("Cook chicken", "Add curry and coconut milk", "Simmer"),
            prepTimeMinutes = 15,
            cookTimeMinutes = 35,
            servings = 4,
            difficulty = "Medium",
            cuisine = "Indian",
            caloriesPerServing = 450,
            tags = listOf("Dinner", "Spicy"),
            userId = 4,
            image = "",
            rating = 4.7,
            reviewCount = 87,
            mealType = listOf("Dinner")
        ),
        RecipeEntity(
            id = 5,
            name = "Pancakes",
            ingredients = listOf("Flour", "Milk", "Eggs", "Maple Syrup"),
            instructions = listOf("Mix ingredients", "Cook on skillet", "Serve with syrup"),
            prepTimeMinutes = 5,
            cookTimeMinutes = 15,
            servings = 2,
            difficulty = "Easy",
            cuisine = "American",
            caloriesPerServing = 350,
            tags = listOf("Breakfast", "Sweet"),
            userId = 5,
            image = "",
            rating = 4.3,
            reviewCount = 56,
            mealType = listOf("Breakfast")
        ),
        RecipeEntity(
            id = 6,
            name = "Beef Tacos",
            ingredients = listOf("Tortillas", "Ground Beef", "Lettuce", "Cheese", "Salsa"),
            instructions = listOf("Cook beef", "Assemble tacos with toppings"),
            prepTimeMinutes = 10,
            cookTimeMinutes = 15,
            servings = 3,
            difficulty = "Easy",
            cuisine = "Mexican",
            caloriesPerServing = 400,
            tags = listOf("Dinner", "Quick"),
            userId = 6,
            image = "",
            rating = 4.5,
            reviewCount = 73,
            mealType = listOf("Lunch", "Dinner")
        ),
        RecipeEntity(
            id = 7,
            name = "Tomato Soup",
            ingredients = listOf("Tomatoes", "Onion", "Garlic", "Cream"),
            instructions = listOf("Cook vegetables", "Blend", "Add cream"),
            prepTimeMinutes = 10,
            cookTimeMinutes = 25,
            servings = 4,
            difficulty = "Easy",
            cuisine = "International",
            caloriesPerServing = 180,
            tags = listOf("Soup", "Vegetarian"),
            userId = 7,
            image = "",
            rating = 4.1,
            reviewCount = 33,
            mealType = listOf("Lunch")
        ),
        RecipeEntity(
            id = 8,
            name = "Sushi Rolls",
            ingredients = listOf("Sushi Rice", "Nori", "Salmon", "Avocado"),
            instructions = listOf("Cook rice", "Assemble rolls"),
            prepTimeMinutes = 20,
            cookTimeMinutes = 0,
            servings = 2,
            difficulty = "Hard",
            cuisine = "Japanese",
            caloriesPerServing = 300,
            tags = listOf("Lunch", "Seafood"),
            userId = 8,
            image = "",
            rating = 4.8,
            reviewCount = 50,
            mealType = listOf("Lunch", "Dinner")
        ),
        RecipeEntity(
            id = 9,
            name = "Chocolate Cake",
            ingredients = listOf("Flour", "Cocoa Powder", "Eggs", "Sugar", "Butter"),
            instructions = listOf("Mix ingredients", "Bake at 350°F", "Cool and frost"),
            prepTimeMinutes = 15,
            cookTimeMinutes = 40,
            servings = 8,
            difficulty = "Medium",
            cuisine = "American",
            caloriesPerServing = 450,
            tags = listOf("Dessert", "Sweet"),
            userId = 9,
            image = "",
            rating = 4.6,
            reviewCount = 110,
            mealType = listOf("Dessert")
        ),
        RecipeEntity(
            id = 10,
            name = "Grilled Salmon",
            ingredients = listOf("Salmon Fillet", "Lemon", "Olive Oil"),
            instructions = listOf("Season salmon", "Grill until cooked"),
            prepTimeMinutes = 5,
            cookTimeMinutes = 15,
            servings = 2,
            difficulty = "Easy",
            cuisine = "International",
            caloriesPerServing = 350,
            tags = listOf("Dinner", "Seafood"),
            userId = 10,
            image = "",
            rating = 4.7,
            reviewCount = 65,
            mealType = listOf("Dinner")
        ),
        RecipeEntity(
            id = 11,
            name = "Vegetable Stir Fry",
            ingredients = listOf("Broccoli", "Carrots", "Bell Peppers", "Soy Sauce"),
            instructions = listOf("Chop vegetables", "Stir fry with sauce"),
            prepTimeMinutes = 10,
            cookTimeMinutes = 10,
            servings = 3,
            difficulty = "Easy",
            cuisine = "Chinese",
            caloriesPerServing = 220,
            tags = listOf("Lunch", "Vegetarian"),
            userId = 11,
            image = "",
            rating = 4.4,
            reviewCount = 40,
            mealType = listOf("Lunch", "Dinner")
        ),
        RecipeEntity(
            id = 12,
            name = "Omelette",
            ingredients = listOf("Eggs", "Cheese", "Spinach"),
            instructions = listOf("Beat eggs", "Cook on skillet", "Add fillings"),
            prepTimeMinutes = 5,
            cookTimeMinutes = 10,
            servings = 1,
            difficulty = "Easy",
            cuisine = "French",
            caloriesPerServing = 250,
            tags = listOf("Breakfast"),
            userId = 12,
            image = "",
            rating = 4.2,
            reviewCount = 28,
            mealType = listOf("Breakfast")
        ),
        RecipeEntity(
            id = 13,
            name = "Guacamole",
            ingredients = listOf("Avocado", "Lime", "Onion", "Tomato"),
            instructions = listOf("Mash avocado", "Add other ingredients", "Mix well"),
            prepTimeMinutes = 10,
            cookTimeMinutes = 0,
            servings = 2,
            difficulty = "Easy",
            cuisine = "Mexican",
            caloriesPerServing = 150,
            tags = listOf("Snack", "Vegetarian"),
            userId = 13,
            image = "",
            rating = 4.5,
            reviewCount = 35,
            mealType = listOf("Snack")
        ),
        RecipeEntity(
            id = 14,
            name = "Beef Stew",
            ingredients = listOf("Beef", "Potatoes", "Carrots", "Onions", "Beef Broth"),
            instructions = listOf("Brown beef", "Add vegetables and broth", "Simmer for 2 hours"),
            prepTimeMinutes = 20,
            cookTimeMinutes = 120,
            servings = 6,
            difficulty = "Medium",
            cuisine = "International",
            caloriesPerServing = 500,
            tags = listOf("Dinner", "Comfort Food"),
            userId = 14,
            image = "",
            rating = 4.6,
            reviewCount = 70,
            mealType = listOf("Dinner")
        ),
        RecipeEntity(
            id = 15,
            name = "French Toast",
            ingredients = listOf("Bread", "Eggs", "Milk", "Cinnamon"),
            instructions = listOf("Mix eggs and milk", "Dip bread", "Cook on skillet"),
            prepTimeMinutes = 5,
            cookTimeMinutes = 10,
            servings = 2,
            difficulty = "Easy",
            cuisine = "French",
            caloriesPerServing = 300,
            tags = listOf("Breakfast", "Sweet"),
            userId = 15,
            image = "",
            rating = 4.3,
            reviewCount = 45,
            mealType = listOf("Breakfast")
        ),
        RecipeEntity(
            id = 16,
            name = "Pad Thai",
            ingredients = listOf("Rice Noodles", "Tofu", "Peanuts", "Bean Sprouts", "Pad Thai Sauce"),
            instructions = listOf("Cook noodles", "Stir fry ingredients", "Add sauce"),
            prepTimeMinutes = 15,
            cookTimeMinutes = 15,
            servings = 2,
            difficulty = "Medium",
            cuisine = "Thai",
            caloriesPerServing = 400,
            tags = listOf("Dinner", "Noodles"),
            userId = 16,
            image = "",
            rating = 4.7,
            reviewCount = 60,
            mealType = listOf("Lunch", "Dinner")
        ),
        RecipeEntity(
            id = 17,
            name = "Apple Pie",
            ingredients = listOf("Apples", "Flour", "Butter", "Sugar", "Cinnamon"),
            instructions = listOf("Prepare crust", "Fill with apples", "Bake"),
            prepTimeMinutes = 20,
            cookTimeMinutes = 50,
            servings = 6,
            difficulty = "Medium",
            cuisine = "American",
            caloriesPerServing = 350,
            tags = listOf("Dessert", "Sweet"),
            userId = 17,
            image = "",
            rating = 4.5,
            reviewCount = 80,
            mealType = listOf("Dessert")
        ),
        RecipeEntity(
            id = 18,
            name = "Shrimp Scampi",
            ingredients = listOf("Shrimp", "Garlic", "Butter", "Lemon", "Parsley"),
            instructions = listOf("Cook shrimp with garlic", "Add butter and lemon", "Serve"),
            prepTimeMinutes = 10,
            cookTimeMinutes = 10,
            servings = 2,
            difficulty = "Medium",
            cuisine = "Italian",
            caloriesPerServing = 300,
            tags = listOf("Dinner", "Seafood"),
            userId = 18,
            image = "",
            rating = 4.6,
            reviewCount = 55,
            mealType = listOf("Dinner")
        ),
        RecipeEntity(
            id = 19,
            name = "Minestrone Soup",
            ingredients = listOf("Tomatoes", "Beans", "Pasta", "Vegetables", "Broth"),
            instructions = listOf("Cook vegetables", "Add beans and broth", "Simmer"),
            prepTimeMinutes = 15,
            cookTimeMinutes = 30,
            servings = 4,
            difficulty = "Easy",
            cuisine = "Italian",
            caloriesPerServing = 180,
            tags = listOf("Lunch", "Vegetarian", "Soup"),
            userId = 19,
            image = "",
            rating = 4.4,
            reviewCount = 25,
            mealType = listOf("Lunch", "Dinner")
        ),
        RecipeEntity(
            id = 20,
            name = "Chocolate Chip Cookies",
            ingredients = listOf("Flour", "Sugar", "Butter", "Chocolate Chips", "Eggs"),
            instructions = listOf("Mix ingredients", "Scoop onto baking sheet", "Bake"),
            prepTimeMinutes = 10,
            cookTimeMinutes = 12,
            servings = 24,
            difficulty = "Easy",
            cuisine = "American",
            caloriesPerServing = 150,
            tags = listOf("Dessert", "Snack", "Sweet"),
            userId = 20,
            image = "",
            rating = 4.8,
            reviewCount = 200,
            mealType = listOf("Dessert", "Snack")
        )
    )
}
